name: VickiFreedomMod
main: me.totalfreedom.totalfreedommod.TotalFreedomMod
version: ${tfm.build.version}
description: Plugin for the Vicki Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials]
authors: [Madgeek1450, Prozza, Loooll, NotAnOperator]

# plugin.yml is no longer used to define commands.
